# Generated by Django 3.0.5 on 2020-05-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0002_auto_20200524_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='group',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='department',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_profile',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.DeleteModel(
            name='Lector',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
