# Generated by Django 3.0.5 on 2020-05-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('univer_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_shift', models.CharField(choices=[('1 смена', 'Первая смена'), ('2 смена', 'Вторая смена'), ('Вч. смена', 'Вечерняя смена')], default='1 смена', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of_study', models.CharField(choices=[('Нечетная н.', 'Нч. неделя'), ('Четная н.', 'Чт. неделя')], default='Нечетная н.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LectorAttachedDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer_structure.Discipline')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer_structure.Lector')),
            ],
        ),
        migrations.CreateModel(
            name='DayStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studydays', to='schedule.Week')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_course', to='univer_structure.CourseNumber')),
                ('degree_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_degree', to='univer_structure.Degree')),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_in_gr', to='univer_structure.Group')),
            ],
        ),
        migrations.CreateModel(
            name='CourseScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Понедельник', 'Пн'), ('Вторник', 'Вт'), ('Среда', 'Ср'), ('Четверг', 'Чт'), ('Пятница', 'Пт'), ('Суббота', 'Сб')], max_length=20)),
                ('times_of_study', models.CharField(choices=[('8:00-9:30', '1.ПАРА 8:00-9:30'), ('9:40-11:10', '2.ПАРА 9:40-11:10'), ('11:20-12:50', '3.ПАРА 11:20-12:50'), ('13:00-14:30', '4.ПАРА 13:00-14:30'), ('14:40-16:10', '5.ПАРА 14:40-16:10'), ('16:20-17:50', '6.ПАРА 16:20-17:50'), ('18:00-19:30', '7.ПАРА 18:00-19:30'), ('19:40-21:10', '8.ПАРА 19:40-21:10')], max_length=30)),
                ('auditorium_of_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_auditorium', to='univer_structure.Auditorium')),
                ('discipline_of_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_discipline', to='univer_structure.Discipline')),
                ('lector_of_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lector', to='univer_structure.Lector')),
                ('students_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_students', to='schedule.CourseStudent')),
            ],
        ),
    ]
