# Generated by Django 3.0.5 on 2020-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daystudy',
            name='days_of_week',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.RenameField(
            model_name='coursescheduleitem',
            old_name='auditorium_of_course',
            new_name='auditorium',
        ),
        migrations.RenameField(
            model_name='coursescheduleitem',
            old_name='discipline_of_course',
            new_name='discipline',
        ),
        migrations.RenameField(
            model_name='coursescheduleitem',
            old_name='students_course',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='coursescheduleitem',
            old_name='lector_of_course',
            new_name='lector',
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='course_number',
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='degree_name',
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='name_of_shift',
            field=models.CharField(choices=[('1 смена', 'Первая смена'), ('2 смена', 'Вторая смена'), ('Вч. смена', 'Вечерняя смена')], default='1 смена', max_length=20),
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='week_of_study',
            field=models.CharField(choices=[('Нечетная н.', 'Нч. неделя'), ('Четная н.', 'Чт. неделя')], default='Нечетная н.', max_length=20),
        ),
        migrations.DeleteModel(
            name='DayStudy',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
