# Generated by Django 3.0.5 on 2020-06-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0003_auto_20200602_1620'),
        ('schedule', '0002_auto_20200529_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_shift', models.CharField(choices=[('1 смена', 'Первая смена'), ('2 смена', 'Вторая смена'), ('Вч. смена', 'Вечерняя смена')], default='1 смена', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(choices=[('8:00-9:30', '1.ПАРА 8:00-9:30'), ('9:40-11:10', '2.ПАРА 9:40-11:10'), ('11:20-12:50', '3.ПАРА 11:20-12:50'), ('13:00-14:30', '4.ПАРА 13:00-14:30'), ('14:40-16:10', '5.ПАРА 14:40-16:10'), ('16:20-17:50', '6.ПАРА 16:20-17:50'), ('18:00-19:30', '7.ПАРА 18:00-19:30'), ('19:40-21:10', '8.ПАРА 19:40-21:10')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursescheduleitem',
            name='name_of_shift',
        ),
        migrations.RemoveField(
            model_name='coursescheduleitem',
            name='times_of_study',
        ),
        migrations.RemoveField(
            model_name='coursescheduleitem',
            name='week_of_study',
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='group_number',
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='half_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='intensity',
            field=models.CharField(choices=[('1 раз в неделю', '1р. в нед.'), ('Через неделю', '1р. в 2 нед.')], default='Через неделю', max_length=15),
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='potok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='quantity_z',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='week_of_study',
            field=models.CharField(choices=[('Нечетная н.', 'Нч. неделя'), ('Четная н.', 'Чт. неделя')], default='Нечетная н.', max_length=20),
        ),
        migrations.AlterField(
            model_name='lectorattacheddiscipline',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_discipline', to='univer_structure.Discipline'),
        ),
        migrations.AlterField(
            model_name='lectorattacheddiscipline',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_lectors', to='univer_structure.Lector'),
        ),
    ]
