# Generated by Django 3.0.5 on 2020-06-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200602_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescheduleitem',
            name='type_discipline',
            field=models.CharField(choices=[('Лк. зн.', 'Лекционное. занятие'), ('Пр. зн.', 'Практическое. занятие.'), ('Лаб. зн.', 'Лабораторное. занятие.')], default='Лк. зн.', max_length=10),
        ),
    ]
