# Generated by Django 3.0.5 on 2020-06-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_coursescheduleitem_type_discipline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectorattacheddiscipline',
            options={'verbose_name_plural': 'Преподаватели и их дисциплины'},
        ),
    ]
