# Generated by Django 3.0.5 on 2020-06-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0013_auto_20200603_1040'),
        ('schedule', '0005_auto_20200603_1014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectorattacheddiscipline',
            unique_together={('lector', 'discipline')},
        ),
    ]
