# Generated by Django 3.0.5 on 2020-06-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0014_remove_discipline_max_number_students'),
        ('schedule', '0008_auto_20200603_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_number_students', models.PositiveIntegerField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructors', to='univer_structure.Lector')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_disciplines', to='univer_structure.Discipline')),
            ],
            options={
                'verbose_name_plural': 'Курсы обучения',
            },
        ),
    ]
