# Generated by Django 3.0.5 on 2020-06-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_number_students',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
