# Generated by Django 3.0.5 on 2020-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0030_remove_discipline_hours'),
        ('schedule', '0010_auto_20200604_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.PositiveSmallIntegerField(blank=True, default=18, null=True)),
                ('practice', models.PositiveSmallIntegerField(blank=True, default=36, null=True)),
                ('laboratory', models.PositiveSmallIntegerField(blank=True, default=36, null=True)),
                ('discipline', models.ManyToManyField(related_name='disciplinelessons', to='univer_structure.Discipline')),
            ],
            options={
                'verbose_name_plural': 'Занятия по дисциплинам',
            },
        ),
        migrations.CreateModel(
            name='GroupAttachedLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(related_name='attachedgroups', to='univer_structure.Group', verbose_name='Группы')),
                ('lessons', models.ManyToManyField(related_name='groupslessons', to='schedule.DisciplineLessons', verbose_name='Занятия')),
            ],
            options={
                'verbose_name_plural': 'Группы и их дисциплины',
            },
        ),
    ]
