# Generated by Django 3.0.5 on 2020-06-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_disciplinelessons_groupattachedlessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinelessons',
            name='laboratory',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplinelessons',
            name='lecture',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplinelessons',
            name='practice',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
