# Generated by Django 3.0.5 on 2020-06-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20200609_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupattachedlessons',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='groupattachedlessons',
            name='lessons',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='GroupAttachedLessons',
        ),
    ]
