# Generated by Django 3.0.5 on 2020-06-12 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0032_auto_20200610_1857'),
        ('schedule', '0015_auto_20200611_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinelessons',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessongroup', to='univer_structure.Group'),
        ),
    ]
