# Generated by Django 3.0.5 on 2020-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_disciplinelessons_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='times',
            old_name='times',
            new_name='time',
        ),
        migrations.AddField(
            model_name='times',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'Пн'), ('Вторник', 'Вт'), ('Среда', 'Ср'), ('Четверг', 'Чт'), ('Пятница', 'Пт'), ('Суббота', 'Сб')], default='Понедельник', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='times',
            name='week_type',
            field=models.CharField(choices=[('Нечетная н.', 'Нч. неделя'), ('Четная н.', 'Чт. неделя')], default='Нечетная н.', max_length=30),
            preserve_default=False,
        ),
    ]
