# Generated by Django 3.0.5 on 2020-06-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0034_auto_20200613_1125'),
        ('schedule', '0017_auto_20200613_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursescheduleitem',
            name='day',
        ),
        migrations.RemoveField(
            model_name='coursescheduleitem',
            name='type_discipline',
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='class_type',
            field=models.CharField(choices=[('lecture', 'Лекционное. занятие'), ('practice', 'Практическое. занятие.'), ('laboratory', 'Лабораторное. занятие.')], default='lecture', max_length=10),
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='schedule.Times'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursescheduleitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_students', to='univer_structure.Group'),
        ),
    ]
