# Generated by Django 3.0.5 on 2020-05-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_user', '0003_auto_20200529_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_auditorium', models.CharField(choices=[('Лекц. а.', 'Лекц. ауд.'), ('Практ. а.', 'Практик. ауд.'), ('Лаб. а.', 'Лаб. ауд.'), ('Каф. а.', 'Аудитория кафедры')], default='Лекц. а.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_degree', models.CharField(choices=[('Бакалавриат', 'Бакалавриат'), ('Специалитет', 'Специалитет'), ('Магистратура', 'Магистратура'), ('Аспирантура', 'Аспирантура')], default='Бакалавриат', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_degree', models.CharField(choices=[('Лк. зн.', 'Лекционное. занятие'), ('Пр. зн.', 'Практическое. занятие.'), ('Лаб. зн.', 'Лабораторное. занятие.')], default='Лк. зн.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_study', models.CharField(choices=[('ОЧ', 'Очная'), ('ЗЧ', 'Заочная')], default='ОЧ', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='univer_structure.Group')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_user.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StaffOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_user.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_staffs', to='univer_structure.Department')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_user.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='univer_structure.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectors', to='univer_structure.Department')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_user.UserProfileInfo')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='univer_structure.Specialty'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='univer_structure.Institute'),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lectors', models.ManyToManyField(to='univer_structure.Lector')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='univer_structure.Faculty'),
        ),
        migrations.CreateModel(
            name='CourseNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_numbers', models.CharField(choices=[('0 курс', 'Подготовительный курс'), ('1 курс', 'Первый курс'), ('2 курс', 'Второй курс'), ('3 курс', 'Третий курс'), ('4 курс', 'Четвертый курс'), ('5 курс', 'Пятый курс')], default='1 курс', max_length=10)),
                ('program_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursenumbers', to='univer_structure.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='univer_structure.Corpus')),
            ],
        ),
    ]
