# Generated by Django 3.0.5 on 2020-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200529_1631'),
        ('univer_structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursenumber',
            name='program_degree',
        ),
        migrations.DeleteModel(
            name='DisciplineType',
        ),
        migrations.AddField(
            model_name='discipline',
            name='type_discipline',
            field=models.CharField(choices=[('Лк. зн.', 'Лекционное. занятие'), ('Пр. зн.', 'Практическое. занятие.'), ('Лаб. зн.', 'Лабораторное. занятие.')], default='Лк. зн.', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='course_number',
            field=models.CharField(choices=[('0 курс', 'Подготовительный курс'), ('1 курс', 'Первый курс'), ('2 курс', 'Второй курс'), ('3 курс', 'Третий курс'), ('4 курс', 'Четвертый курс'), ('5 курс', 'Пятый курс')], default='1 курс', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='degree',
            field=models.CharField(choices=[('Бакалавриат', 'Бакалавриат'), ('Специалитет', 'Специалитет'), ('Магистратура', 'Магистратура'), ('Аспирантура', 'Аспирантура')], default='Бакалавриат', max_length=30),
        ),
        migrations.DeleteModel(
            name='CourseNumber',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
    ]
