# Generated by Django 3.0.5 on 2020-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0002_auto_20200529_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditoriumType',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='lectors',
        ),
        migrations.AddField(
            model_name='auditorium',
            name='capacity',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='type_of_auditorium',
            field=models.CharField(choices=[('Б.Лекц. а.', 'Б.Лекц. ауд.'), ('М.Лекц. а.', 'М.Лекц. ауд.'), ('Практ. а.', 'Практик. ауд.'), ('Лаб. а.', 'Лаб. ауд.'), ('Каф. а.', 'Аудитория кафедры')], default='М.Лекц. а.', max_length=10),
        ),
        migrations.AddField(
            model_name='discipline',
            name='hours',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='max_number_students',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='quantity_s',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
