# Generated by Django 3.0.5 on 2020-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0005_auto_20200602_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='type_of_auditorium',
            field=models.CharField(choices=[('Б.Лекц. а.', 'Б.Лекционная'), ('М.Лекц. а.', 'М.Лекционная'), ('Практ. а.', 'Аудитория практических з.'), ('Лаб. а.', 'Лабораторная'), ('Каф. а.', 'Аудитория кафедры')], default='М.Лекц. а.', max_length=10),
        ),
    ]
