# Generated by Django 3.0.5 on 2020-06-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0006_auto_20200602_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditorium',
            options={'verbose_name': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name': 'Интситуты'},
        ),
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='staffdepartment',
            options={'verbose_name': 'Сотрудники кафедр'},
        ),
        migrations.AlterModelOptions(
            name='staffother',
            options={'verbose_name': 'Другие сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='capacity',
            field=models.PositiveIntegerField(default=25, verbose_name='Вмеестимость'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='univer_structure.Corpus', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='type_of_auditorium',
            field=models.CharField(choices=[('Б.Лекц. а.', 'Большая Лекционная'), ('М.Лекц. а.', 'Малая Лекционная'), ('Практ. а.', 'Аудитория практических з.'), ('Аудитория', 'Аудитория'), ('Лаб. а.', 'Лабораторная'), ('Уч. Лаб.', 'Учебная Лабораторная'), ('Уч. класс', 'Учебный класс'), ('Каф. а.', 'Аудитория кафедры')], default='М.Лекц. а.', max_length=10, verbose_name='Тип аудитории'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название корпуса'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='univer_structure.Faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название кафедры'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='univer_structure.Institute', verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название факультета'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course_number',
            field=models.CharField(choices=[('0 курс', 'Подготовительный курс'), ('1 курс', 'Первый курс'), ('2 курс', 'Второй курс'), ('3 курс', 'Третий курс'), ('4 курс', 'Четвертый курс'), ('5 курс', 'Пятый курс')], default='1 курс', max_length=10, verbose_name='Номер курса'),
        ),
        migrations.AlterField(
            model_name='group',
            name='degree',
            field=models.CharField(choices=[('Бакалавриат', 'Бакалавриат'), ('Специалитет', 'Специалитет'), ('Магистратура', 'Магистратура'), ('Аспирантура', 'Аспирантура')], default='Бакалавриат', max_length=30, verbose_name='Ступень обучения'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='quantity_s',
            field=models.CharField(max_length=5, null=True, verbose_name='Количество студентов'),
        ),
        migrations.AlterField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='univer_structure.Specialty', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название института'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='univer_structure.Faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название специальности'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_of_study',
            field=models.CharField(choices=[('ОЧ', 'Очная'), ('ЗЧ', 'Заочная')], default='ОЧ', max_length=10, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='univer_structure.Group', verbose_name='Группа'),
        ),
    ]
