# Generated by Django 3.0.5 on 2020-06-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0007_auto_20200602_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditorium',
            options={'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name_plural': 'Интситуты'},
        ),
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='staffdepartment',
            options={'verbose_name_plural': 'Сотрудники кафедр'},
        ),
        migrations.AlterModelOptions(
            name='staffother',
            options={'verbose_name_plural': 'Другие сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Студенты'},
        ),
    ]
