# Generated by Django 3.0.5 on 2020-06-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0010_auto_20200602_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='type_discipline',
        ),
    ]
