# Generated by Django 3.0.5 on 2020-06-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0011_remove_discipline_type_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='hours',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='max_number_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
