# Generated by Django 3.0.5 on 2020-06-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0012_auto_20200603_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
