# Generated by Django 3.0.5 on 2020-06-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0013_auto_20200603_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='max_number_students',
        ),
    ]
