# Generated by Django 3.0.5 on 2020-06-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0014_remove_discipline_max_number_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corpus_departments', to='univer_structure.Corpus', verbose_name='Корпус'),
        ),
    ]
