# Generated by Django 3.0.5 on 2020-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0015_department_corpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='max_number_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
