# Generated by Django 3.0.5 on 2020-06-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0022_auto_20200603_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='univer_structure.Department'),
        ),
    ]
