# Generated by Django 3.0.5 on 2020-06-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0023_discipline_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='quantity_s',
            new_name='quantity_students',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='max_number_students',
        ),
        migrations.AddField(
            model_name='auditorium',
            name='dept',
            field=models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, related_name='dept_aucitoriums', to='univer_structure.Department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpusauditoriums', to='univer_structure.Corpus', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupspecialties', to='univer_structure.Specialty', verbose_name='Специальность'),
        ),
    ]
