# Generated by Django 3.0.5 on 2020-06-07 13:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0025_auto_20200607_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='type_discipline',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Лк. зн.', 'Лекции'), ('Пр. зн.', 'Практика'), ('Лаб. зн.', 'Лабораторные работы')], max_length=24, null=True, verbose_name='Вид учебных занятий'),
        ),
    ]
