# Generated by Django 3.0.5 on 2020-06-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0027_lector_disciplines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='department',
        ),
        migrations.AddField(
            model_name='lector',
            name='department',
            field=models.ManyToManyField(to='univer_structure.Department'),
        ),
    ]
