# Generated by Django 3.0.5 on 2020-06-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0029_auto_20200607_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='hours',
        ),
    ]
