# Generated by Django 3.0.5 on 2020-06-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0030_remove_discipline_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название профиля')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='univer_structure.Specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name_plural': 'Профили Специальностей',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='univer_structure.Profile'),
        ),
    ]
