# Generated by Django 3.0.5 on 2020-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20200610_1857'),
        ('univer_structure', '0031_auto_20200609_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lessons',
            field=models.ManyToManyField(related_name='groupslessons', to='schedule.DisciplineLessons', verbose_name='Занятия'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='department',
            field=models.ManyToManyField(related_name='disciplinedepts', to='univer_structure.Department'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='department',
            field=models.ManyToManyField(related_name='lectordepartments', to='univer_structure.Department'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='disciplines',
            field=models.ManyToManyField(related_name='lectordisciplines', to='univer_structure.Discipline'),
        ),
    ]
