# Generated by Django 3.0.5 on 2020-06-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0032_auto_20200610_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='lessons',
        ),
    ]
