# Generated by Django 3.0.5 on 2020-06-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer_structure', '0033_remove_group_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='department',
        ),
        migrations.AddField(
            model_name='discipline',
            name='department',
            field=models.ForeignKey(default=65, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='univer_structure.Department'),
            preserve_default=False,
        ),
    ]
